In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\govin\Desktop\Dataset\Predict_customer_Will_Leave_the-Bank-master\BankCustomers.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [7]:
X = df.iloc[:,3:13]

In [8]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [16]:
X.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [11]:
y = df.iloc[:,-1]

In [15]:
y.isna().sum()

0

In [18]:
geo = pd.get_dummies(X['Geography'], drop_first = True)
gender = pd.get_dummies(X['Gender'], drop_first = True)

In [24]:
X = pd.concat([X,geo,gender], axis = 1)

In [25]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0          1               1        101348.88        0      0     0  
1          0               1        112542.58        0      1     0  
2          1               0        113931.57        0      0     0  
3          0               0         93826.63        0      0     0  
4          1               1         79084.10        0      1     0

In [27]:
X = X.drop(['Gender', 'Geography'], axis = 1)

In [28]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [42]:
len(X.columns)

11

In [43]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [44]:
x_train

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
7389          667   34       5       0.00              2          1   
9275          427   42       1   75681.52              1          1   
2995          535   29       2  112367.34              1          1   
5316          654   40       5  105683.63              1          1   
356           850   57       8  126776.30              2          1   
...           ...  ...     ...        ...            ...        ...   
9225          594   32       4  120074.97              2          1   
4859          794   22       4  114440.24              1          1   
3264          738   35       5  161274.05              2          1   
9845          590   38       9       0.00              2          1   
2732          623   48       1  108076.33              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain  Male  
7389               0        163830.64        0      1     0  
9275               1         57098.00        1      0     1  
2995               0        185630.76        0      0     0  
5316               0        173617.09        0      1     1  
356                1        132298.49        0      1     0  
...              ...              ...      ...    ...   ...  
9225               1        162961.79        1      0     0  
4859               1        107753.07        0      1     0  
3264               0        181429.87        0      0     1  
9845               1        148750.16        0      1     0  
2732               0        118855.26        1      0     0  

[8000 rows x 11 columns]

Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)

In [46]:
x_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [47]:
x_test = sc.transform(x_test)

In [48]:
x_test


array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

# ANN model building

In [51]:
import tensorflow as tf

In [54]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [55]:
classifier = Sequential()

In [56]:
classifier.add(Dense(activation = 'relu', input_dim = 11, units = 6, kernel_initializer = 'uniform'))

In [57]:
classifier.add(Dense(activation = 'relu', units = 6, kernel_initializer = 'uniform'))

In [58]:
classifier.add(Dense(activation = 'sigmoid', units = 1, kernel_initializer = 'uniform'))

In [59]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [62]:
classifier.fit(x_train, y_train, batch_size = 10, epochs = 15)

Epoch 1/15
800/800 [==============================] - 1s 492us/step - loss: 0.5568 - accuracy: 0.7988
Epoch 2/15
800/800 [==============================] - 0s 501us/step - loss: 0.4260 - accuracy: 0.8004
Epoch 3/15
800/800 [==============================] - 0s 503us/step - loss: 0.4292 - accuracy: 0.7868
Epoch 4/15
800/800 [==============================] - 0s 491us/step - loss: 0.4142 - accuracy: 0.8234
Epoch 5/15
800/800 [==============================] - 0s 519us/step - loss: 0.4217 - accuracy: 0.8229
Epoch 6/15
800/800 [==============================] - 0s 508us/step - loss: 0.4133 - accuracy: 0.8345
Epoch 7/15
800/800 [==============================] - 0s 508us/step - loss: 0.4205 - accuracy: 0.8273
Epoch 8/15
800/800 [==============================] - 0s 511us/step - loss: 0.4037 - accuracy: 0.8385
Epoch 9/15
800/800 [==============================] - 0s 514us/step - loss: 0.4117 - accuracy: 0.8348
Epoch 10/15
800/800 [==============================] - 0s 496us/step - loss: 0.409

In [63]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

In [64]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [66]:
accuracy_score(y_test, y_pred)

0.842

In [67]:
confusion_matrix(y_test, y_pred)

array([[1560,   35],
       [ 281,  124]], dtype=int64)